<a href="https://colab.research.google.com/github/saheedniyi02/fpl-ai/blob/master/weekly_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def convert_minutes(val):
    """CONVERTS MINUTES TO A CATEGORICAL OUTPUT"""
    if val > 10:
        return 1
    else:
        return 0

In [ ]:
import pandas as pd
import numpy as np
#from utils import convert_minutes
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    mean_squared_error,
    mean_absolute_error,
    f1_score,
)

gameweek = 9
for i in range(1, gameweek + 1):
    results = pd.read_csv(f"/content/drive/MyDrive/Fplpredict /datasets/2023-24/results/GW{i}.csv")
    results["minutes_actual"] = results["minutes"].apply(convert_minutes)

    goalkeeper_minutes = pd.read_csv(f"/content/drive/MyDrive/Fplpredict /predicted_dataset/GW{i}/goalkeepers_minutes.csv")
    defender_minutes = pd.read_csv(f"/content/drive/MyDrive/Fplpredict /predicted_dataset/GW{i}/defenders_minutes.csv")
    midfielder_minutes = pd.read_csv(f"/content/drive/MyDrive/Fplpredict /predicted_dataset/GW{i}/midfielders_minutes.csv")
    foward_minutes = pd.read_csv(f"/content/drive/MyDrive/Fplpredict /predicted_dataset/GW{gameweek}/forwards_minutes.csv")
    #/storage/emulated/0/fpl_reserved/
    # load points
    goalkeeper_points = pd.read_csv(f"/content/drive/MyDrive/Fplpredict /predicted_dataset/GW{i}/goalkeepers_points.csv")
    midfielder_points = pd.read_csv(f"/content/drive/MyDrive/Fplpredict /predicted_dataset/GW{i}/midfielders_points.csv")
    foward_points = pd.read_csv(f"/content/drive/MyDrive/Fplpredict /predicted_dataset/GW{i}/forwards_points.csv")
    defender_points = pd.read_csv(f"/content/drive/MyDrive/Fplpredict /predicted_dataset/GW{i}/defenders_points.csv")

    print(f"\n\nGAMEWEEK {i}")
    # calculate goalkeepers
    print("\nGOALKEEPERS")
    goalkeeper_minutes = pd.merge(
        goalkeeper_minutes,
        results[["name", "minutes_actual"]],
        left_on="name",
        right_on="name",
        how="left",
    )
    goalkeeper_minutes = goalkeeper_minutes.dropna()

    # print(goalkeeper_minutes[pd.isna(goalkeeper_minutes["minutes_actual"])]["name"])
    #goalkeeper_minutes = goalkeeper_minutes.dropna()
    print(
        confusion_matrix(
            goalkeeper_minutes["minutes"], goalkeeper_minutes["minutes_actual"]
        )
    )
    acc_score = accuracy_score(
        goalkeeper_minutes["minutes"], goalkeeper_minutes["minutes_actual"]
    )
    print(f"accuracy score {acc_score}")
    f1_score_ = f1_score(
        goalkeeper_minutes["minutes"], goalkeeper_minutes["minutes_actual"]
    )
    print(f"F1 SCORE {f1_score_}")

    goalkeeper_points = pd.merge(
        goalkeeper_points,
        results[["name", "minutes_actual", "total_points"]],
        left_on="name",
        right_on="name",
        how="left",
    )

    goalkeeper_points = goalkeeper_points.dropna()
    rmse = np.sqrt(
        mean_squared_error(
            goalkeeper_points["points"], goalkeeper_points["total_points"]
        )
    )
    print(f"Root Mean Square Error:{rmse}")

    # calculate defenders
    print("\nDEFENDERS")
    defender_minutes = pd.merge(
        defender_minutes,
        results[["name", "minutes_actual"]],
        left_on="name",
        right_on="name",
        how="left",
    )

    # print(defender_minutes[pd.isna(defender_minutes["minutes_actual"])]["name"])

    defender_minutes = defender_minutes.dropna()
    print(
        confusion_matrix(
            defender_minutes["minutes"], defender_minutes["minutes_actual"]
        )
    )

    acc_score = accuracy_score(
        defender_minutes["minutes"], defender_minutes["minutes_actual"]
    )
    print(f"Accuracy score {acc_score}")

    f1_score_ = f1_score(
        defender_minutes["minutes"], defender_minutes["minutes_actual"]
    )
    print(f"F1 SCORE {f1_score_}")

    defender_points = pd.merge(
        defender_points,
        results[["name", "minutes_actual", "total_points"]],
        left_on="name",
        right_on="name",
        how="left",
    )
    defender_points = defender_points.dropna()
    rmse = np.sqrt(
        mean_squared_error(defender_points["points"], defender_points["total_points"])
    )
    print(f"Root Mean Square Error:{rmse}")

    # calculate midfielders
    print("\nMIDFIELDERS")
    midfielder_minutes = pd.merge(
        midfielder_minutes,
        results[["name", "minutes_actual"]],
        left_on="name",
        right_on="name",
        how="left",
    )

    # print(midfielder_minutes[pd.isna(midfielder_minutes["minutes_actual"])]["name"])

    midfielder_minutes = midfielder_minutes.dropna()
    print(
        confusion_matrix(
            midfielder_minutes["minutes"], midfielder_minutes["minutes_actual"]
        )
    )

    acc_score = accuracy_score(
        midfielder_minutes["minutes"], midfielder_minutes["minutes_actual"]
    )
    print(f"Accuracy score {acc_score}")

    f1_score_ = f1_score(
        midfielder_minutes["minutes"], midfielder_minutes["minutes_actual"]
    )
    print(f"F1 SCORE {f1_score_}")

    midfielder_points = pd.merge(
        midfielder_points,
        results[["name", "minutes_actual", "total_points"]],
        left_on="name",
        right_on="name",
        how="left",
    )

    midfielder_points = midfielder_points.dropna()

    rmse = np.sqrt(
        mean_squared_error(
            midfielder_points["points"], midfielder_points["total_points"]
        )
    )

    print(f"Root Mean Square Error:{rmse}")

    # calculate fowards
    print("\nFOWARDS")
    foward_minutes = pd.merge(
        foward_minutes,
        results[["name", "minutes_actual"]],
        left_on="name",
        right_on="name",
        how="left",
    )

    # print(foward_minutes[pd.isna(foward_minutes["minutes_actual"])]["name"])

    foward_minutes = foward_minutes.dropna()

    print(confusion_matrix(foward_minutes["minutes"], foward_minutes["minutes_actual"]))
    acc_score = accuracy_score(
        foward_minutes["minutes"], foward_minutes["minutes_actual"]
    )
    print(f"Accuracy score {acc_score}")

    f1_score_ = f1_score(foward_minutes["minutes"], foward_minutes["minutes_actual"])
    print(f"F1 SCORE {f1_score_}")
    foward_points = pd.merge(
        foward_points,
        results[["name", "minutes_actual", "total_points"]],
        left_on="name",
        right_on="name",
        how="left",
    )

    foward_points = foward_points.dropna()
    rmse = np.sqrt(
        mean_squared_error(foward_points["points"], foward_points["total_points"])
    )

    print(f"Root Mean Square Error:{rmse}")



GAMEWEEK 1

GOALKEEPERS
[[35 12]
 [ 9 20]]
accuracy score 0.7236842105263158
F1 SCORE 0.6557377049180328
Root Mean Square Error:3.1496595829404033

DEFENDERS
[[54 26]
 [29 46]]
Accuracy score 0.6451612903225806
F1 SCORE 0.6258503401360543
Root Mean Square Error:2.986576736457505

MIDFIELDERS
[[55 22]
 [36 64]]
Accuracy score 0.672316384180791
F1 SCORE 0.6881720430107526
Root Mean Square Error:2.588794607155526

FOWARDS
[[33  5]
 [11 27]]
Accuracy score 0.7894736842105263
F1 SCORE 0.7714285714285714
Root Mean Square Error:3.69022654753307


GAMEWEEK 2

GOALKEEPERS
[[49  0]
 [ 0 18]]
accuracy score 1.0
F1 SCORE 1.0
Root Mean Square Error:3.803972412739226

DEFENDERS
[[96 20]
 [14 67]]
Accuracy score 0.8274111675126904
F1 SCORE 0.7976190476190476
Root Mean Square Error:2.8026442812927996

MIDFIELDERS
[[122  17]
 [ 13  97]]
Accuracy score 0.8795180722891566
F1 SCORE 0.8660714285714286
Root Mean Square Error:3.2177723354372163

FOWARDS
[[35  4]
 [12 22]]
Accuracy score 0.7808219178082192
